# Generated by Django 5.2.15 on 2026-09-25 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0130_projectcustomsettings'),
        ('db', '0140_taxonomy_project_states_and_labels'),
    ]

    operations = [
    ]
