# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 5.2.15 on 2026-09-25 05:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0142_automationrule"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationExecution",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_id", models.UUIDField()),
                ("status", models.CharField(default="pending", max_length=16)),
                ("error", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("issue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="db.issue")),
                ("rule", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="db.automationrule")),
            ],
            options={
                "db_table": "automation_executions",
                "constraints": [
                    models.UniqueConstraint(fields=("rule", "event_id"), name="automation_rule_event_unique")
                ],
            },
        ),
    ]
