# Generated by Django 5.2.15 on 2026-09-25 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0143_automation_execution"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubConnection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("installation_id", models.PositiveBigIntegerField(unique=True)),
                ("account_login", models.CharField(max_length=255)),
                ("github_user_id", models.PositiveBigIntegerField()),
                ("authorized_repository_ids", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connected_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="db.workspace")),
            ],
        ),
        migrations.CreateModel(
            name="GitHubConnectNonce",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("stage", models.CharField(default="installation", max_length=16)),
                ("installation_id", models.PositiveBigIntegerField(null=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="db.workspace")),
            ],
        ),
        migrations.CreateModel(
            name="GitHubRepositoryMapping",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("repository_id", models.PositiveBigIntegerField()),
                ("full_name", models.CharField(max_length=255)),
                ("is_private", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sync_status", models.CharField(default="pending", max_length=16)),
                ("sync_error", models.CharField(blank=True, max_length=200)),
                ("last_synced_at", models.DateTimeField(null=True)),
                (
                    "connection",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="db.githubconnection"),
                ),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="db.project")),
            ],
        ),
        migrations.CreateModel(
            name="GitHubRelease",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("github_id", models.PositiveBigIntegerField()),
                ("tag_name", models.CharField(max_length=255)),
                ("name", models.CharField(blank=True, max_length=1000)),
                ("body", models.TextField(blank=True)),
                ("draft", models.BooleanField(default=False)),
                ("prerelease", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("remote_updated_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mapping",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="db.githubrepositorymapping"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GitHubPullRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("github_id", models.PositiveBigIntegerField()),
                ("number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=1000)),
                ("body", models.TextField(blank=True)),
                ("head_ref", models.CharField(blank=True, max_length=500)),
                ("state", models.CharField(default="open", max_length=16)),
                ("draft", models.BooleanField(default=False)),
                ("merged_at", models.DateTimeField(null=True)),
                ("review_state", models.CharField(default="pending", max_length=32)),
                ("reviewed_at", models.DateTimeField(null=True)),
                ("remote_updated_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mapping",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="db.githubrepositorymapping"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GitHubWebhookDelivery",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("event", models.CharField(max_length=64)),
                ("body_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("status", models.CharField(default="queued", max_length=16)),
                ("error", models.CharField(blank=True, max_length=100)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="db.githubconnection"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GitHubIssueLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_manual", models.BooleanField(default=False)),
                ("is_suppressed", models.BooleanField(default=False)),
                ("issue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="db.issue")),
                (
                    "pull_request",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="db.githubpullrequest"),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("issue", "pull_request"), name="github_issue_pr_link")],
            },
        ),
        migrations.AddConstraint(
            model_name="githubrepositorymapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("connection", "repository_id"),
                name="github_active_repository_mapping",
            ),
        ),
        migrations.AddConstraint(
            model_name="githubrelease",
            constraint=models.UniqueConstraint(fields=("mapping", "github_id"), name="github_mapping_release"),
        ),
        migrations.AddConstraint(
            model_name="githubpullrequest",
            constraint=models.UniqueConstraint(fields=("mapping", "number"), name="github_mapping_pr_number"),
        ),
    ]
