# Generated by Django 5.2.15 on 2026-09-25 13:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0143_automation_execution"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppConnection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("origin", models.URLField(max_length=2048)),
                ("current_version", models.CharField(blank=True, default="", max_length=120)),
                ("enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="app_connection", to="db.project"
                    ),
                ),
            ],
            options={
                "db_table": "app_connections",
            },
        ),
        migrations.CreateModel(
            name="PageReview",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(default="queued", max_length=20)),
                ("request", models.JSONField(default=dict)),
                ("evidence", models.JSONField(default=list)),
                ("results", models.JSONField(default=dict)),
                ("error", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="page_reviews", to="db.project"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "db_table": "page_reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
