# Generated by Django 5.2.15 on 2026-09-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0144_issue_template'),
        ('db', '0145_time_entry'),
        ('db', '0147_merge_0143_and_0146'),
    ]

    operations = [
    ]
