# Generated by Django 5.2.15 on 2026-09-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0144_github_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubwebhookdelivery",
            name="installation_id",
            field=models.PositiveBigIntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="githubwebhookdelivery",
            name="next_retry_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="githubwebhookdelivery",
            name="processing_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="githubwebhookdelivery",
            name="repository_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
