# Generated by Django 5.2.15 on 2026-09-25 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0143_automation_execution'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_id', models.CharField(max_length=32, unique=True)),
                ('team_name', models.CharField(max_length=255)),
                ('team_domain', models.CharField(blank=True, max_length=255)),
                ('slack_user_id', models.CharField(max_length=32)),
                ('bot_user_id', models.CharField(max_length=32)),
                ('bot_token_encrypted', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='SlackChannelMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=32)),
                ('channel_name', models.CharField(max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_status', models.CharField(default='pending', max_length=16)),
                ('sync_error', models.CharField(blank=True, max_length=200)),
                ('last_synced_at', models.DateTimeField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.project')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.slackconnection')),
            ],
        ),
        migrations.CreateModel(
            name='SlackConnectNonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('stage', models.CharField(default='authorization', max_length=16)),
                ('team_id', models.CharField(blank=True, max_length=32, null=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='SlackEventDelivery',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('team_id', models.CharField(db_index=True, max_length=32, null=True)),
                ('channel_id', models.CharField(max_length=32, null=True)),
                ('processing_attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(null=True)),
                ('event', models.CharField(max_length=64)),
                ('body_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('error', models.CharField(blank=True, max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(null=True)),
                ('connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.slackconnection')),
            ],
        ),
        migrations.CreateModel(
            name='SlackMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.CharField(max_length=32)),
                ('user_id', models.CharField(blank=True, max_length=32)),
                ('thread_ts', models.CharField(blank=True, max_length=32)),
                ('text', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(null=True)),
                ('remote_updated_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.slackchannelmapping')),
            ],
        ),
        migrations.CreateModel(
            name='SlackIssueLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manual', models.BooleanField(default=False)),
                ('is_suppressed', models.BooleanField(default=False)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.issue')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.slackmessage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='slackchannelmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('connection', 'channel_id'), name='slack_active_channel_mapping'),
        ),
        migrations.AddConstraint(
            model_name='slackmessage',
            constraint=models.UniqueConstraint(fields=('mapping', 'ts'), name='slack_mapping_message_ts'),
        ),
        migrations.AddConstraint(
            model_name='slackissuelink',
            constraint=models.UniqueConstraint(fields=('issue', 'message'), name='slack_issue_message_link'),
        ),
    ]
