# Generated by Django 5.2.15 on 2026-09-25 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0150_merge_delivery_retry'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubconnection',
            name='host',
            field=models.CharField(default='github.com', max_length=255),
        ),
        migrations.AddField(
            model_name='githubconnectnonce',
            name='host',
            field=models.CharField(default='github.com', max_length=255),
        ),
        migrations.AddField(
            model_name='githubconnectnonce',
            name='origin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='githubwebhookdelivery',
            name='host',
            field=models.CharField(default='github.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='githubconnection',
            name='installation_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='githubconnectnonce',
            name='stage',
            field=models.CharField(default='manifest', max_length=16),
        ),
        migrations.CreateModel(
            name='GitHubApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(default='github.com', max_length=255)),
                ('app_id', models.PositiveBigIntegerField()),
                ('slug', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.TextField()),
                ('private_key', models.TextField()),
                ('webhook_secret', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='githubconnection',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.githubapp'),
        ),
        migrations.AddField(
            model_name='githubconnectnonce',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.githubapp'),
        ),
        migrations.AddField(
            model_name='githubwebhookdelivery',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.githubapp'),
        ),
        migrations.AddConstraint(
            model_name='githubconnection',
            constraint=models.UniqueConstraint(fields=('host', 'installation_id'), name='github_connection_host_installation'),
        ),
        migrations.AddConstraint(
            model_name='githubapp',
            constraint=models.UniqueConstraint(fields=('host', 'app_id'), name='github_app_host_app_id'),
        ),
    ]
