# Generated by Django 5.2.15 on 2026-09-25 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0148_merge_20260925_1720'),
        ('db', '0160_slack_delivery'),
        ('db', '0163_affinepagemap'),
        ('db', '0164_github_click_connect'),
        ('db', '0165_asana_sync_sidecar'),
        ('db', '0170_infralink'),
    ]

    operations = [
    ]
