# Generated by Django 5.2.15 on 2026-09-26 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0176_github_project_automation'),
        ('db', '0177_github_checks_reviews'),
    ]

    operations = [
    ]
