# Generated by Django 5.2.15 on 2026-09-26 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0179_github_automation_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubautomationrule',
            options={'ordering': ('created_at', 'id')},
        ),
    ]
