# Generated by Django 5.2.15 on 2026-09-26 05:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0180_automation_rule_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackAppSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=64)),
                ('client_secret_encrypted', models.TextField(blank=True)),
                ('signing_secret_encrypted', models.TextField(blank=True)),
                ('app_id', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
