# Generated by Django 5.2.15 on 2026-09-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0181_slack_app_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackchannelmapping',
            name='notify_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slackchannelmapping',
            name='notify_state_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slackchannelmapping',
            name='notify_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slackchannelmapping',
            name='notify_commented',
            field=models.BooleanField(default=False),
        ),
    ]
