# Generated by Django 5.2.15 on 2026-09-30 03:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0183_slack_presence_beat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIActionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('entity_type', models.CharField(blank=True, max_length=32)),
                ('entity_id', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=16)),
                ('input_excerpt', models.TextField(blank=True)),
                ('output_excerpt', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_action_audits', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_action_audits', to='db.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_action_audits', to='db.workspace')),
            ],
            options={
                'verbose_name': 'AI Action Audit',
                'verbose_name_plural': 'AI Action Audits',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='db_aiaction_workspa_27cde3_idx'), models.Index(fields=['entity_type', 'entity_id'], name='db_aiaction_entity__4e9add_idx')],
            },
        ),
    ]
