# Generated by Django 5.2.15 on 2026-09-30 05:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0184_ai_action_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIIssueSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('label', 'Label'), ('assignee', 'Assignee'), ('priority', 'Priority'), ('summary', 'Summary')], max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_triage_decisions', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_suggestions', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_issue_suggestions', to='db.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_issue_suggestions', to='db.workspace')),
            ],
            options={
                'verbose_name': 'AI Issue Suggestion',
                'verbose_name_plural': 'AI Issue Suggestions',
                'ordering': ('-created_at',),
            },
        ),
    ]
