# Generated by Django 5.2.15 on 2026-10-01 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0190_asana_assignee_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackAgentJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_id', models.CharField(max_length=32)),
                ('channel_id', models.CharField(db_index=True, max_length=32)),
                ('thread_ts', models.CharField(blank=True, default='', max_length=32)),
                ('requester_slack_user_id', models.CharField(max_length=32)),
                ('instructions', models.TextField(blank=True, default='')),
                ('job_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(db_index=True, default='dispatching', max_length=24)),
                ('last_event_id', models.CharField(blank=True, default='', max_length=64)),
                ('last_reply_ts', models.CharField(blank=True, default='', max_length=32)),
                ('preview', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.slackconnection')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.issue')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('thread_ts', ''), _negated=True), fields=('channel_id', 'thread_ts'), name='slack_agent_job_thread'), models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='slack_agent_job_idempotency')],
            },
        ),
    ]
