# Generated by Django 5.2.15 on 2026-10-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0191_slack_agent_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackagentjob',
            name='event_log',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='slackagentjob',
            name='origin',
            field=models.CharField(default='slack', max_length=8),
        ),
        migrations.AlterField(
            model_name='slackagentjob',
            name='channel_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='slackagentjob',
            name='requester_slack_user_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='slackagentjob',
            name='team_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
