# Generated by Django 4.2.30 on 2026-07-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_instance_is_current_version_deprecated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='is_telemetry_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
